
server.port: 20002
eureka.instance.hostname: server2
eureka.client.service-url.defaultZone: http://192.168.1.61:20001/eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false