server:
  port : 20002

eureka:
  instance:
    hostname : server2
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://server1:20001/eureka/,http://server2:20002/eureka/